### ISSUE TITLE
Remove you client 

### ISSUE THREAD

**Issue by funky-monkey** [JagCesar/Tesla-API#40]
Hey, 

First off awesome package you created!
Second; maybe remove your client id/secret from "**Sources/TeslaAPI/Requests/AuthenticateRequest.swift**". Not sure if this still works, have not tested it but better to obfuscate it. You can use Github Secrets for this. 

Take care, 
Sidney

**Comment by JagCesar** [comment]
Hey,

These are the identifiers required to be used. The client attaches these to the request, identifying to the backend as the official Tesla app.

I'm fairly sure this code no longer works, Tesla updated their authentication system some time ago.

Closing ticket, feel free to re-open if I missed something.

**Comment by funky-monkey** [comment]
I understand these are required to make requests, I'm saying don't post your API keys/secrets to github. Github has a feature called [Github Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets)' to still make use of these secrets. When developing locally you can use environmental vars so you don't expose your secrets on the internet
Depending on what API you use, and you do post stuff like this to Github, others can use this information to make requests from your account, using up all your API credits and thus letting you pay for their usage. Just be aware

**Comment by JagCesar** [comment]
These are not my identifiers. These are the required identifiers for anyone to make the requests. It's a way for Tesla to make sure only their app can access their endpoints.

I don't see the benefit of using GitHub secrets when these keys are required to be used by everyone.
